spring.profiles.active=oci

spring.application.name=mobi-auth
spring.threads.virtual.enabled=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

## MOBI AUTH
mobi.auth.client-id=mobi-client
mobi.auth.client-secret=mobi-secret
mobi.auth.redirect-uri=http://127.0.0.1:9090/login/oauth2/code/mobi-client
mobi.auth.scope=urn:opc:idm:__myscopes__

## Spring OAuth2 Client Configuration
spring.security.oauth2.client.registration.oci.client-id=${MOBI_AUTH_CLIENT_ID}
spring.security.oauth2.client.registration.oci.client-secret=${MOBI_AUTH_CLIENT_SECRET}

## Spring OAuth2 Provider Configuration
spring.security.oauth2.client.provider.oci.issuer-uri=${MOBI_OCI_ISSUER_URI}
spring.security.oauth2.client.provider.oci.token-uri=${MOBI_OCI_TOKEN_URI}